// Code generated by MockGen. DO NOT EDIT.
// Source: route256/loms/internal/app/services (interfaces: Loms)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/mocks/loms.go -package=services route256/loms/internal/app/services Loms
//
// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	models "route256/loms/internal/app/models"

	gomock "go.uber.org/mock/gomock"
)

// MockLoms is a mock of Loms interface.
type MockLoms struct {
	ctrl     *gomock.Controller
	recorder *MockLomsMockRecorder
}

// MockLomsMockRecorder is the mock recorder for MockLoms.
type MockLomsMockRecorder struct {
	mock *MockLoms
}

// NewMockLoms creates a new mock instance.
func NewMockLoms(ctrl *gomock.Controller) *MockLoms {
	mock := &MockLoms{ctrl: ctrl}
	mock.recorder = &MockLomsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoms) EXPECT() *MockLomsMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockLoms) CreateOrder(arg0 context.Context, arg1 int64, arg2 []models.OrderItem) (models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockLomsMockRecorder) CreateOrder(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockLoms)(nil).CreateOrder), arg0, arg1, arg2)
}
