// Code generated by MockGen. DO NOT EDIT.
// Source: route256/loms/internal/app/services (interfaces: EventProducer)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/services/event_producer_mock.go -package=services route256/loms/internal/app/services EventProducer
//
// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	models "route256/loms/internal/app/models"

	gomock "go.uber.org/mock/gomock"
)

// MockEventProducer is a mock of EventProducer interface.
type MockEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockEventProducerMockRecorder
}

// MockEventProducerMockRecorder is the mock recorder for MockEventProducer.
type MockEventProducerMockRecorder struct {
	mock *MockEventProducer
}

// NewMockEventProducer creates a new mock instance.
func NewMockEventProducer(ctrl *gomock.Controller) *MockEventProducer {
	mock := &MockEventProducer{ctrl: ctrl}
	mock.recorder = &MockEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProducer) EXPECT() *MockEventProducerMockRecorder {
	return m.recorder
}

// OrderStatusChangedEventEmit mocks base method.
func (m *MockEventProducer) OrderStatusChangedEventEmit(arg0 context.Context, arg1 models.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OrderStatusChangedEventEmit", arg0, arg1)
}

// OrderStatusChangedEventEmit indicates an expected call of OrderStatusChangedEventEmit.
func (mr *MockEventProducerMockRecorder) OrderStatusChangedEventEmit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderStatusChangedEventEmit", reflect.TypeOf((*MockEventProducer)(nil).OrderStatusChangedEventEmit), arg0, arg1)
}
