image: golang:1.21

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

stages:
  - check
  - build

test cart:
  stage: check
  script:
    - cd cart
    - go vet ./...
    - go test -v -race -coverprofile profile.cov.tmp ./...
    - cat profile.cov.tmp | grep -v "_mock.go" | grep -v "pb.go" > cover.out
    - go tool cover -func cover.out
  coverage: "/\\(statements\\)(?:\\s+)?(\\d+(?:\\.\\d+)?%)/"


lint cart:
  stage: check
  image: golangci/golangci-lint:v1.54.2
  script:
    - cd cart
    - golangci-lint run -v

fmt cart:
  stage: check
  script:
    - go install mvdan.cc/gofumpt@latest
    - cd cart
    - test -z "$(gofumpt -d -e . | tee /dev/stderr)"

test loms:
  stage: check
  script:
    - cd loms
    - go vet ./...
    - go test -v -race -coverprofile profile.cov.tmp ./...
    - cat profile.cov.tmp | grep -v "_mock.go" | grep -v "pb.go" > cover.out
    - go tool cover -func cover.out
  coverage: "/\\(statements\\)(?:\\s+)?(\\d+(?:\\.\\d+)?%)/"

lint loms:
  stage: check
  image: golangci/golangci-lint:v1.54.2
  script:
    - cd cart
    - golangci-lint run -v

fmt loms:
  stage: check
  script:
    - go install mvdan.cc/gofumpt@latest
    - cd loms
    - test -z "$(gofumpt -d -e . | tee /dev/stderr)"

build cart:
  stage: build
  script:
    - go build ./cart/cmd/app


build loms:
  stage: build
  script:
    - go build ./loms/cmd/app
