// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ChangeReserveOfSkuByAmount(ctx context.Context, arg ChangeReserveOfSkuByAmountParams) (pgconn.CommandTag, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error)
	CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) error
	GetBySku(ctx context.Context, sku int64) (int64, error)
	GetExpiredOrdersWithStatus(ctx context.Context, arg GetExpiredOrdersWithStatusParams) ([]int64, error)
	GetFailedMessage(ctx context.Context, lockedBy pgtype.Text) ([]Outbox, error)
	GetLockedUnsentMessage(ctx context.Context, lockedBy pgtype.Text) ([]Outbox, error)
	GetOrderById(ctx context.Context, id int64) ([]GetOrderByIdRow, error)
	LockUnsentMessages(ctx context.Context, lockedBy pgtype.Text) error
	SaveOutboxMessage(ctx context.Context, arg SaveOutboxMessageParams) error
	SetMessageFailed(ctx context.Context, arg SetMessageFailedParams) error
	SetMessageSent(ctx context.Context, id int64) error
	UnlockUnsentMessages(ctx context.Context, lockedBy pgtype.Text) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
