// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: queries.sql

package queries

import (
	"context"
)

const changeReserveOfSkuByAmount = `-- name: ChangeReserveOfSkuByAmount :exec
update stocks set count = count+$1 where sku=$2
`

type ChangeReserveOfSkuByAmountParams struct {
	Count int64 `json:"count"`
	Sku   int64 `json:"sku"`
}

func (q *Queries) ChangeReserveOfSkuByAmount(ctx context.Context, arg ChangeReserveOfSkuByAmountParams) error {
	_, err := q.db.Exec(ctx, changeReserveOfSkuByAmount, arg.Count, arg.Sku)
	return err
}

const getBySku = `-- name: GetBySku :one
select count from stocks where sku=$1
`

// noinspection SqlInsertValuesForFile
func (q *Queries) GetBySku(ctx context.Context, sku int64) (int64, error) {
	row := q.db.QueryRow(ctx, getBySku, sku)
	var count int64
	err := row.Scan(&count)
	return count, err
}
