// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"context"
)

type Querier interface {
	ChangeReserveOfSkuByAmount(ctx context.Context, arg ChangeReserveOfSkuByAmountParams) error
	// noinspection SqlInsertValuesForFile
	GetBySku(ctx context.Context, sku int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
