// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"context"
)

type Querier interface {
	// noinspection SqlInsertValuesForFile
	GetBySku(ctx context.Context, sku int64) (int64, error)
	RemoveReserveSku(ctx context.Context, arg RemoveReserveSkuParams) error
	ReserveSku(ctx context.Context, arg ReserveSkuParams) error
}

var _ Querier = (*Queries)(nil)
