// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"context"
)

type Querier interface {
	// noinspection SqlInsertValuesForFile
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
}

var _ Querier = (*Queries)(nil)
