version: '3.5'

services:
  app:
    image: route256/cart
    container_name: cart
    build:
      context:  ../
      dockerfile: docker/Dockerfile
    command: /cart
    volumes:
      - ../:/usr/src/app/
    ports:
      - "8083:8083"
      - "8080:8080"