version: '3.5'

services:
  app:
    image: route256/loms
    container_name: loms
    build:
      context:  ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app/
    ports:
      - "8083:8083"
      - "8080:8080"
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "user=postgres password=password host=db dbname=loms sslmode=disable"
    command: sh -c '/usr/src/app/docker/wait-for-it.sh -t 5 db:5432 -- /loms'
    depends_on:
      - db
  db:
    image: postgres
    container_name: loms-db
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"