// Code generated by MockGen. DO NOT EDIT.
// Source: route256/cart/internal/app/services (interfaces: CartStorage)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/mocks/cart_storage.go -package=services route256/cart/internal/app/services CartStorage
//
// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	models "route256/cart/internal/app/models"

	gomock "go.uber.org/mock/gomock"
)

// MockCartStorage is a mock of CartStorage interface.
type MockCartStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCartStorageMockRecorder
}

// MockCartStorageMockRecorder is the mock recorder for MockCartStorage.
type MockCartStorageMockRecorder struct {
	mock *MockCartStorage
}

// NewMockCartStorage creates a new mock instance.
func NewMockCartStorage(ctrl *gomock.Controller) *MockCartStorage {
	mock := &MockCartStorage{ctrl: ctrl}
	mock.recorder = &MockCartStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartStorage) EXPECT() *MockCartStorageMockRecorder {
	return m.recorder
}

// SaveItem mocks base method.
func (m *MockCartStorage) SaveItem(arg0 context.Context, arg1 models.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveItem indicates an expected call of SaveItem.
func (mr *MockCartStorageMockRecorder) SaveItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveItem", reflect.TypeOf((*MockCartStorage)(nil).SaveItem), arg0, arg1)
}
