// Code generated by MockGen. DO NOT EDIT.
// Source: route256/cart/internal/app/services (interfaces: LomsService)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/mocks/loms.go -package=services route256/cart/internal/app/services LomsService
//
// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	models "route256/cart/internal/app/models"

	gomock "go.uber.org/mock/gomock"
)

// MockLomsService is a mock of LomsService interface.
type MockLomsService struct {
	ctrl     *gomock.Controller
	recorder *MockLomsServiceMockRecorder
}

// MockLomsServiceMockRecorder is the mock recorder for MockLomsService.
type MockLomsServiceMockRecorder struct {
	mock *MockLomsService
}

// NewMockLomsService creates a new mock instance.
func NewMockLomsService(ctrl *gomock.Controller) *MockLomsService {
	mock := &MockLomsService{ctrl: ctrl}
	mock.recorder = &MockLomsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLomsService) EXPECT() *MockLomsServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockLomsService) CreateOrder(arg0 context.Context, arg1 int64, arg2 []models.CartItem) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockLomsServiceMockRecorder) CreateOrder(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockLomsService)(nil).CreateOrder), arg0, arg1, arg2)
}

// GetStocksInfo mocks base method.
func (m *MockLomsService) GetStocksInfo(arg0 context.Context, arg1 uint32) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocksInfo", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocksInfo indicates an expected call of GetStocksInfo.
func (mr *MockLomsServiceMockRecorder) GetStocksInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocksInfo", reflect.TypeOf((*MockLomsService)(nil).GetStocksInfo), arg0, arg1)
}
