{
 "title": "services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "95th Percentile of Handlers Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"AddItem\"}[$__rate_interval])))",
     "legendFormat": "AddItem"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"Checkout\"}[$__rate_interval])))",
     "legendFormat": "Checkout"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"List\"}[$__rate_interval])))",
     "legendFormat": "List"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"OrderCreate\"}[$__rate_interval])))",
     "legendFormat": "OrderCreate"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"StockInfo\"}[$__rate_interval])))",
     "legendFormat": "StockInfo"
    }
   ]
  },
  {
   "title": "RPS of handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"OK\"}[$__rate_interval])",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "panics count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(grpc_req_panics_recovered_total[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}