// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

type CartItem struct {
	ID     int64 `json:"id"`
	Sku    int64 `json:"sku"`
	Count  int64 `json:"count"`
	UserID int64 `json:"user_id"`
}
