// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"context"
)

type Querier interface {
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteCartItemsByUserId(ctx context.Context, userID int64) error
	GetCartItemsByUserId(ctx context.Context, userID int64) ([]CartItem, error)
	// noinspection SqlInsertValuesForFile
	SaveCartItem(ctx context.Context, arg SaveCartItemParams) error
}

var _ Querier = (*Queries)(nil)
